#!/bin/sh
dot -Tpng graph1.dot > graph1.png
dot -Tpng graph2.dot > graph2.png
dot -Tpng graph3.dot > graph3.png
dot -Tpng graph4.dot > graph4.png
dot -Tpng k5g.dot > k5g.png
dot -Tpng k5u.dot > k5u.png
